# Generated by Django 3.1.6 on 2022-07-31 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('mood', models.CharField(choices=[('great', '😝 • Great'), ('good', '😆 • Good'), ('usual', '🙂 • Usual'), ('bad', '😢 • Bad'), ('terrible', '😭 • Terrible')], max_length=30)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('reads', models.PositiveIntegerField(default=0)),
                ('reported', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
